title: 米迪
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: Grimxiaojun
# 头像里面的描述
avatarDesc: 爱生活，爱网络
url: "http://grimxiaojun.github.io"

comment:
    # disqus: leopard
    duoshuo: Midiya

# Social
social:
    weibo: ----
    github: Midiya
    # twitter: 
    mail: 1076735024@qq.com

ga:
    id: UA-96239281-2
    host: auto





permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"
